name: arm-reprex

on:
  workflow_dispatch:
    inputs:
      code:
        description: "R code to run"
        required: true
        default: "sessionInfo(); library(bigmemory)"

jobs:
  run:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: r-lib/actions/setup-r@v2
      - run: install.packages("pak", repos="https://cloud.r-project.org")
        shell: Rscript {0}
      - run: pak::pkg_install("bigmemory")
        shell: Rscript {0}
      - run: pak::pkg_install("pbreheny/plmmr")
        shell: Rscript {0}
      - name: Run reprex
        timeout-minutes: 1
        run: |
          cat <<'EOF' > reprex.R
          ${{ inputs.code }}
          EOF
          Rscript reprex.R
